USE tigerdb;
DROP PROCEDURE IF EXISTS SP_HELLO;
DELIMITER $$
CREATE PROCEDURE SP_HELLO()
    BEGIN
        DECLARE STR CHAR(20) DEFAULT 'POPI';
        SET STR = 'HELLO, WORDL!';
        SELECT STR;
    END $$
DELIMITER ;

CALL SP_HELLO();